# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evaluateteam.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from scorecalculation import Ui_MainWindow as score
import sqlite3
cr=sqlite3.connect("FantasyCricket.db")
curcr=cr.cursor()


class Ui_MainWindow(object):
    def __init__(self):
        self.scoreDialog=QtWidgets.QMainWindow()
        self.score_screen=score()
        self.score_screen.setupUi(self.scoreDialog)
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 633)
        MainWindow.setStyleSheet("background-color: rgb(250, 15, 135);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 731, 81))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.fontComboBox = QtWidgets.QComboBox(MainWindow)
        self.fontComboBox.setGeometry(QtCore.QRect(100, 100, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(9)
        self.fontComboBox.setFont(font)
        self.fontComboBox.setStyleSheet("background-color: rgb(170, 255, 255);")
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(9)
        self.fontComboBox.setObjectName("ComboBox")
        self.fontComboBox.setEnabled(True)
        self.fontComboBox_2 = QtWidgets.QComboBox(MainWindow)
        self.fontComboBox_2.setGeometry(QtCore.QRect(540, 100, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(9)
        self.fontComboBox_2.setFont(font)
        self.fontComboBox_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.fontComboBox_2.setObjectName("fontComboBox_2")
        self.fontComboBox_2.addItem("")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(90, 150, 731, 321))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(170, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(430, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(170, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(510, 20, 68, 19))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.listWidget_2 = QtWidgets.QListWidget(self.frame)
        self.listWidget_2.setGeometry(QtCore.QRect(420, 51, 311, 271))
        self.listWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listWidget_2.setObjectName("listWidget_2")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(10, 50, 311, 271))
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 480, 171, 34))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.finalscore)
        selectedteam=self.fontComboBox.currentText()
        self.changedname(selectedteam)
        self.fontComboBox.currentTextChanged.connect(self.changedname)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Evaluate The Performance of Your Fantasy Cricket Team"))
        self.fontComboBox.setCurrentText(_translate("MainWindow", "Select Team"))
        self.fontComboBox.setItemText(0, _translate("MainWindow", "Select team"))
        self.fontComboBox_2.setCurrentText(_translate("MainWindow", "Select Match"))
        self.fontComboBox_2.setItemText(1, _translate("MainWindow", "Match1"))
        self.label_2.setText(_translate("MainWindow", "Players"))
        self.label_3.setText(_translate("MainWindow", "Points"))
        self.label_4.setText(_translate("MainWindow", "##"))
        self.pushButton.setText(_translate("MainWindow", "Calculate Score"))

        x=curcr.execute("SELECT DISTINCT Name from Teams")
        y=x.fetchall()
        for i in y:
            self.fontComboBox.addItem(i[0])

            
    def changedname(self,t):
        self.listWidget.clear()
        self.listWidget_2.clear()
        y=curcr.execute("SELECT Players from Teams WHERE Name='"+t+"';")
        player=y.fetchall()
        for j in player:
            self.listWidget.addItem(j[0])
        z=curcr.execute("SELECT Value from Teams WHERE Name='"+t+"';")
        value=z.fetchall()
        for k in value:
            self.listWidget_2.addItem(str(k[0]))
    def finalscore(self):
        totalscore=0
        t=self.fontComboBox.currentText()
        z=curcr.execute("SELECT Value from Teams WHERE Name='"+t+"';")
        value=z.fetchall()
        for k in value:
            totalscore+=k[0]
        self.score_screen.label_2.setText(str(totalscore))
        self.scoreDialog.show()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

